// Generated from the CHANGELOG.md [2.0.0] block by Scripts/generate-release-notes.swift.
// DO NOT EDIT BY HAND — regenerate in release prep after updating CHANGELOG.md:
//   swift Scripts/generate-release-notes.swift
// Drift guards: ReleaseNotesGuardTests (version + changelog digest), package-app.sh.

extension ReleaseNotes {
    public static let current = ReleaseNotes(
        version: "2.0.0",
        changelogDigest: "cb479e0c73f61971",
        sections: [
            Section(title: "Added", items: [
                "Optional, off-by-default window-specific machine indicator and switching menu beside the tabs, with local/remote identity, SSH destination, connection status, and a compact sidebar control",
                "Cursor-anchored Insert Path popup (⌥⌘I), with themed file icons, fuzzy Folder/Project search, keyboard navigation, and focus restoration",
                "Common compound emoji and longer combining sequences retain their text through rendering, copy, capture, reflow, and reattachment",
                "Native scrollback thumb dragging and track clicks, honoring the macOS scrollbar preference",
                "Per-pane Activity across attached hosts, with exact-pane navigation, read state, notification snoozing, and hook installation health",
                "Saved Setups with editable layouts, optional startup commands, import/export, and explicit Open versus Open New Copy behavior",
                "Recently Closed layout recovery with fresh shells and up to 20 entries per host",
                "Literal output search across open sessions with case matching, pagination, and source validation before opening results",
                "Fuzzy file and directory selection, Git-aware project paths, and multi-path insertion",
                "Terminal settings import preview with conflicts, supported shortcut mappings, skipped settings, and undo that preserves later edits",
                "Configurable pane spacing in Appearance settings, retaining the 8-point default",
            ]),
            Section(title: "Changed", items: [
                "Warm ASCII glyph-cache lookup avoids unnecessary LRU writes while only one page is populated: 20.6% less time in the recorded 18,800-lookup release benchmark",
                "Unicode width and combining-mark data now use checksum-pinned Unicode 18.0.0 sources",
                "Full-history width reflow avoids decoding blank padding on compact, hard-ended rows: 21% less CPU time in the matched 10,000-line prose benchmark, with text, styling, wrapping, and image anchors preserved",
                "Sparkle is updated to 2.9.6 across SwiftPM and Xcode, incorporating upstream installer and delta-update security fixes",
                "Global-search results separate excerpts from quieter location details, with consistent row spacing and reusable cells",
                "Cleaner title-bar spacing with separate tabs, compact badges, and a 100-column × 30-row fresh-window default based on the configured font and padding",
                "Recessed window chrome gives translucent terminal panes a lighter appearance against the tab bar, sidebar, and gutters while preserving terminal colors and one shared window blur",
                "Flat rectangular terminal and agent badges have balanced spacing, taller marks, and no drop shadow",
                "Onboarding explains persistence and optional notifications accurately, separates permission from agent-hook installation, accommodates smaller screens, and pauses ambient animation while inactive",
                "Regular Metal drawable waits run off the UI thread, keeping typing and output delivery responsive under load while preserving display synchronization",
                "Viewport scrolling rotates rows instead of copying the entire grid",
                "Literal Find reuses its UTF-16 mapping buffer, and daemon output scanners avoid per-byte collection overhead",
                "GUI daemon commands and subscriptions run off the main thread, with captured targets, ordered operations, and stale-result protection",
                "Find uses cancellable background matching across soft wraps; global output search uses expiring pagination without repeatedly materializing whole histories",
                "Accessibility text is cached by content revision and exposes actual visible, cursor, and selection ranges",
                "Decoded history has its own memory ceiling alongside raw output retention; wide rows can reach the byte ceiling before the line limit",
                "Wider horizontal tabs share a rounded container; sidebar tabs use matching height and selected styling",
                "More consistent sidebar spacing, contextual menus, circular hover controls within pills, and darker selected tabs in the default theme",
                "Improved command palette and remote-host sheet readability, slower activity spinners, and clearer connection retry and diagnostic controls",
                "Utility windows enforce usable minimum sizes; saved setup editing shows saving feedback and prevents duplicate submissions",
            ]),
            Section(title: "Fixed", items: [
                "Copy mode preserves newer combining marks when the host segments them differently; copy and search retain correct cell coordinates",
                "Mixed blinking and non-blinking text no longer shares a shaping run while the blink phase is hidden",
                "Make PTY read-source installation atomic with close/respawn, avoiding stale descriptor access and disposal of an inactive dispatch source",
                "PTY draining uses bounded nonblocking reads, preserving queued output when macOS reports zero available bytes before resize or read-source cancellation",
                "Clearing history invalidates warmed capture/search grids and serializes the disk reset with output appends; replacing a shell with cleared history rejects late output from its predecessor",
                "Turning scrollback persistence off preserves an idle pane's screen in memory while deleting its disk snapshot; snapshot writes and deletion are serialized",
                "PTY size and foreground-process queries cannot inspect a recycled descriptor during shell replacement",
                "Lua native-library loading on macOS uses dlopen, restoring loading of libraries in the system cache and removing obsolete loader API use",
                "The isolated preview bundle advertises the same macOS 15 minimum as the app",
                "Rebuilding a nested split cancels temporary resize targets when a neighboring pane returns to its original bounds, preventing a narrow terminal grid inside a full-width pane",
                "Terminal reattachment follows the original resize boundaries, preventing prompt/redraw corruption when output was produced at different widths",
                "Cached daemon capture grids reflow on resize instead of reparsing their entire output history",
                "UI animation completion and drag-pasteboard access honor main-actor isolation; delayed callbacks keep weak ownership",
                "Benchmark comparison and recording now fail when the test process fails, even if the comparison step succeeds",
                "Remote-host renames save atomically and reject name collisions; failed removal preserves the connection",
                "Path insertion reports uncertain command outcomes without leaving Return ready to repeat them",
                "Find and global output search respect IME composition",
                "Image dimensions are checked before decoding",
                "Captured shell output is bounded and stays with the original host; delayed conditional actions cannot execute in a different pane",
                "Cancelled output subscriptions cannot send stale binary frames into a newly reused connection",
                "Coalesced reconnect output retains the sequence of its first byte, preventing skipped output after reattachment",
                "Comfortable pane dividers retain a full-length drag target even when AppKit proposes an empty hit rectangle",
                "Settings refreshes its sidebar background along with text when switching light/dark appearance; the pane-spacing hint reflects the actual default",
                "Input queue exhaustion is reported instead of silently dropping a paste; uncertain writes are never automatically retried",
                "Invalid live configuration retains the last working settings",
                "Idle panes repaint after display invalidation; Quick Terminal uses the same appearance updates as normal windows",
                "Experience descriptions reflect effective session persistence",
                "Socket writes, discovery subprocesses, file-backed graphics reads, and trigger regex work have bounded resource/time behavior",
                "Isolated application homes no longer refresh the normal installed binaries or restart its launchd service",
                "The scrollback setting reaches new, restored, and already attached daemon surfaces instead of leaving their raw replay buffer at 1 MiB",
                "Shells launched without any locale inherit a UTF-8 character locale; explicit locale settings remain unchanged",
                "⌘W closes the active utility window instead of closing a terminal pane behind Settings",
                "A delayed session-backed terminal reconnect can no longer recreate a surface after its pane closes",
                "Marking Activity read or changing snooze preserves the activity's timestamp and does not resolve a blocked process",
                "Path insertion and Go to Directory reject terminal control characters",
            ]),
        ]
    )
}
