// Generated from the CHANGELOG.md [1.13.0] block by Scripts/generate-release-notes.swift.
// DO NOT EDIT BY HAND — regenerate in release prep after updating CHANGELOG.md:
//   swift Scripts/generate-release-notes.swift
// Drift guards: ReleaseNotesGuardTests (version + changelog digest), package-app.sh.

extension ReleaseNotes {
    public static let current = ReleaseNotes(
        version: "1.13.0",
        changelogDigest: "dfca3ee3c2500268",
        sections: [
            Section(title: "Added", items: [
                "Several machines at once",
                "Multiple windows",
                "Notifications replace the notch",
                "Kitty graphics animation",
                "Live Overview and peek thumbnails",
                "Panes from the keyboard, no prefix needed",
                "Every menu command is in the palette",
                "Help ▸ Keyboard Shortcuts (⌘/) lists everything",
                "VoiceOver hears what needs you",
                "Progress you can see",
                "Tab tear-off",
                "Shortcuts from the command palette",
                "Splits that move",
                "Kitty Unicode placeholders",
                "More of the Kitty graphics protocol",
                "Paste into a remote pane",
                "Tailscale discovery that finds Harness",
                "Copy Watch Command",
                "allow-clipboard-read",
            ]),
            Section(title: "Changed", items: [
                "Reattaching paints the screen first",
                "Every pane paints at once when the app comes back",
                "Settings, polished",
                "A first-run tour that's about Harness",
                "Thumbnails cost almost nothing",
                "Faster everywhere it counts",
                "Workspace Overview is a live grid",
                "Idle panes cost a fraction of their scrollback",
                "⌘W closes the focused pane first",
                "Every event name is domain.verb",
                "One target resolver, one API executor",
                "Unnamed sessions have one name everywhere",
                "A crisp light mode",
                "The tab row is level with the traffic lights",
                "Adding a remote host takes one field",
                "A dropped tunnel reconnects itself",
                "Sessions popover",
                "Title-bar tabs are the default; the sidebar is a mode",
                "Title-bar tabs, reworked",
                "Every comfortable pane is an inset card with a header",
                "Panes keep their own cwd and command",
                "Harness Navy",
                "One radius scale",
                "Fresh installs start in Persistent mode",
                "One chrome surface",
                "The daemon is the session",
                "Only the size owner answers terminal queries",
                "Go to Directory (⌥⌘G)",
                "Drag panes by their header",
                "Sessions get names",
                "One attention order everywhere",
                "A Dock tile that shows your agents",
                "VoiceOver",
                "Save and export themes",
                "Owner sizing you can see",
                "attach paints the screen, like tmux",
                "The whole API from Lua",
                "Lua function key bindings work in the app",
                "Everyday CLI verbs",
                "Rex-style targeting",
                "Pipes and formats",
                "Twelve new API methods",
                "HARNESS_PANE",
                "harness-cli run",
                "Targets by name, position, or ID fragment",
                "Consistent exit statuses",
                "Program status (OSC 7501 rev 0.2)",
                "JSON API",
                "Lua 5.1 config, CLI only",
                "Workspace CLI",
                "Craft",
                "Another Mac",
                "Snapshot",
                "The scorecard measures the daemon's own memory",
            ]),
            Section(title: "Fixed", items: [
                "Programs in a pane stop when told to",
                "The Linux daemon builds and tests again",
                "Windows come forward without waiting on their daemon",
                "Rename Tab does something",
                "Exactly one client answers terminal queries",
                "Panes move the way the arrows point",
                "resize-pane counts cells, on the right axis",
                "Layouts and ratios set elsewhere show up",
                "Review fixes for this round",
                "Typing into a frozen pane never holds a thread",
                "Review fixes across this work",
                "Idle parking did what it said",
                "Large scrollback no longer reattaches blank",
                "Reconnecting resumes instead of repainting",
                "A read-only watcher can't resize the pane",
                "capture-pane --format vt keeps every attribute",
                "wait and run --wait on a split pane",
                "process with no --surface",
                "Lua events work",
                "harness.queue does something",
                "api call <command> runs the command",
                "Event stream fixes",
                "Split panes reopen in their own directory",
                "harness-cli copy-mode reaches the app",
                "Idle snapshots don't pile up",
                "Tab peek doesn't block",
                "resize-pane takes a surface",
                "No keychain prompt from the daemon",
                "Card edges are clean",
                "harness-cli --host no longer breaks the app's tunnel",
                "A restored pane starts the new shell on a fresh line",
                "Split gaps are painted",
                "New shells no longer inherit NO_COLOR or a disabled FORCE_COLOR",
                "Light canvases use the light palette",
                "Unlimited scrollback is one ceiling",
                "Split gaps no longer stack",
                "The session switcher and tab peek take the keyboard",
                "Lua keys never stall typing",
                "ssh output can't deadlock",
                "Remote failures say why",
                "remote list shows [connected]",
                "save-layout records what is running",
                "api call session.view",
                "Linux install hint and docs use the real socket",
            ]),
        ]
    )
}
