#!/usr/bin/env swift
//
// generate-width-table.swift — produces `CharacterWidthTable.swift`, the committed O(1) lookup
// tables behind `CharacterWidth.width(of:)`.
//
// Run manually (NOT part of the build) whenever the canonical East-Asian-Width / zero-width ranges
// in `CharacterWidth.swift` change:
//
//   swift Scripts/generate-width-table.swift > \
//     Packages/HarnessTerminalEngine/Sources/HarnessTerminalEngine/Width/CharacterWidthTable.swift
//
// The table is correct *by construction*: every BMP cell is filled by evaluating `referenceWidth`
// (the exact linear-scan semantics of the shipped `CharacterWidth`), and the astral planes are
// emitted as the maximal runs where width ≠ 1. `CharacterWidthTests` re-proves equivalence over
// every scalar 0…0x10FFFF, so a stale table (ranges edited but table not regenerated) fails CI.
//
// The canonical ranges below MUST stay identical to `CharacterWidth.zeroWidthRanges` /
// `CharacterWidth.wideRanges`; the parity test enforces it.

// MARK: - Canonical ranges (mirror of CharacterWidth.swift — kept in sync by CharacterWidthTests)

let zeroWidthRanges: [ClosedRange<UInt32>] = [
    0x0300 ... 0x036F,
    0x0483 ... 0x0489,
    0x0591 ... 0x05BD,
    0x0610 ... 0x061A,
    0x064B ... 0x065F,
    0x0670 ... 0x0670,
    0x06D6 ... 0x06DC,
    0x06DF ... 0x06E4,
    0x0900 ... 0x0902,
    0x093C ... 0x093C,
    0x0941 ... 0x0948,
    0x0E31 ... 0x0E31,
    0x0E34 ... 0x0E3A,
    0x0E47 ... 0x0E4E, // Thai: MAITAIKHU, MAI EK/THO/TRI/CHATTAWA, THANTHAKHAT, NIKHAHIT, YAMAKKAN
    0x1AB0 ... 0x1AFF,
    0x1DC0 ... 0x1DFF,
    0x200B ... 0x200F,
    0x2028 ... 0x202E,
    0x2060 ... 0x2064,
    0x20D0 ... 0x20FF,
    0xFE00 ... 0xFE0F,
    0xFE20 ... 0xFE2F,
    0xFEFF ... 0xFEFF,
    0xE0100 ... 0xE01EF,
]

let wideRanges: [ClosedRange<UInt32>] = [
    0x1100 ... 0x115F,
    0x2329 ... 0x232A,
    0x2E80 ... 0x303E,
    0x3041 ... 0x33FF,
    0x3400 ... 0x4DBF,
    0x4E00 ... 0x9FFF,
    0xA000 ... 0xA4CF,
    0xAC00 ... 0xD7A3,
    0xF900 ... 0xFAFF,
    0xFE10 ... 0xFE19,
    0xFE30 ... 0xFE6F,
    0xFF00 ... 0xFF60,
    0xFFE0 ... 0xFFE6,
    0x1F300 ... 0x1F64F,
    0x1F900 ... 0x1F9FF,
    0x20000 ... 0x2FFFD,
    0x30000 ... 0x3FFFD,
]

// MARK: - Reference width (exact semantics of the shipped CharacterWidth)

func referenceWidth(_ cp: UInt32) -> UInt8 {
    if cp == 0 { return 0 }
    if cp < 0x20 || (cp >= 0x7F && cp < 0xA0) { return 0 }
    for r in zeroWidthRanges where r.contains(cp) { return 0 }
    for r in wideRanges where r.contains(cp) { return 2 }
    return 1
}

// MARK: - BMP two-stage table (256 blocks of 256 codepoints; 2 bits per cell; deduped blocks)

var stage1 = [UInt16](repeating: 0, count: 256)
var blocks: [[UInt8]] = []           // each block is 64 packed bytes (256 cells × 2 bits)
var blockIndex: [[UInt8]: Int] = [:]

for hi in 0 ..< 256 {
    var packed = [UInt8](repeating: 0, count: 64)
    for lo in 0 ..< 256 {
        let cp = UInt32(hi << 8 | lo)
        let code = referenceWidth(cp) & 0x3
        packed[lo >> 2] |= code << UInt8((lo & 3) << 1)
    }
    if let idx = blockIndex[packed] {
        stage1[hi] = UInt16(idx)
    } else {
        let idx = blocks.count
        blocks.append(packed)
        blockIndex[packed] = idx
        stage1[hi] = UInt16(idx)
    }
}

let stage2 = blocks.flatMap { $0 }

// MARK: - Astral planes: maximal runs where width ≠ 1 (binary-searched at lookup)

var astralLo: [UInt32] = []
var astralHi: [UInt32] = []
var astralCode: [UInt8] = []
var cp: UInt32 = 0x10000
while cp <= 0x10FFFF {
    let code = referenceWidth(cp)
    if code != 1 {
        let start = cp
        var end = cp
        while end + 1 <= 0x10FFFF, referenceWidth(end + 1) == code { end += 1 }
        astralLo.append(start)
        astralHi.append(end)
        astralCode.append(code)
        cp = end + 1
    } else {
        cp += 1
    }
}

// MARK: - Emit

func hex(_ v: UInt32) -> String { "0x" + String(v, radix: 16, uppercase: true) }

func emitArray<T>(_ name: String, _ type: String, _ values: [T], perRow: Int, _ fmt: (T) -> String) {
    print("    static let \(name): [\(type)] = [")
    var row: [String] = []
    for (i, v) in values.enumerated() {
        row.append(fmt(v))
        if row.count == perRow || i == values.count - 1 {
            print("        " + row.joined(separator: ", ") + ",")
            row.removeAll(keepingCapacity: true)
        }
    }
    print("    ]")
}

print("""
// GENERATED by Scripts/generate-width-table.swift — DO NOT EDIT BY HAND.
// Re-run the generator if the canonical ranges in CharacterWidth.swift change.
// Correctness is enforced exhaustively by CharacterWidthTests (width == referenceWidth, all scalars).

/// Packed O(1) character-width tables. BMP: a two-stage trie (`stage1` block index → `stage2`
/// 2-bits-per-cell blocks). Astral: maximal non-width-1 runs, binary-searched. Width codes:
/// `0` = zero-width, `1` = narrow, `2` = wide.
enum CharacterWidthTable {
    /// Number of 256-codepoint blocks per BMP row (cp >> 8 indexes `stage1`).
    static let blockBytes = 64
""")
emitArray("stage1", "UInt16", stage1, perRow: 16) { String($0) }
print("")
emitArray("stage2", "UInt8", stage2, perRow: 32) { String($0) }
print("")
emitArray("astralLo", "UInt32", astralLo, perRow: 6) { hex($0) }
print("")
emitArray("astralHi", "UInt32", astralHi, perRow: 6) { hex($0) }
print("")
emitArray("astralCode", "UInt8", astralCode, perRow: 12) { String($0) }
print("}")
