#!/usr/bin/env -S uv run --script
# /// script
# dependencies = ["fonttools==4.62.1"]
# ///
"""Generate compiled, normalized marks from the checked-in logo sources. No network."""
import base64
import hashlib
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET

from fontTools.misc.transform import Identity
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path
from fontTools.svgLib.path.shapes import PathBuilder

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "Apps/Harness/Resources/AgentLogos"
DESTINATION = ROOT / "Apps/Harness/Sources/HarnessApp/UI/AgentIconArt.swift"


def geometry(element, transform=Identity):
    tag = element.tag.split("}")[-1]
    if tag in {"defs", "clipPath", "mask", "style", "metadata"}:
        return
    if "transform" in element.attrib:
        for name, values in re.findall(r"([a-z]+)\(([^)]+)\)", element.attrib["transform"]):
            args = [float(v) for v in re.split(r"[\s,]+", values.strip())]
            if name == "translate":
                transform = transform.translate(*args)
            elif name == "scale":
                transform = transform.scale(*args)
            elif name == "matrix":
                transform = transform.transform(args)
            else:
                raise ValueError(f"Unsupported transform: {name}")
    if tag in {"path", "rect"}:
        builder = PathBuilder()
        shape = ET.Element(tag, {k: v for k, v in element.attrib.items() if k != "transform"})
        builder.add_path_from_element(shape)
        for data in builder.paths:
            pen = RecordingPen()
            parse_path(data, TransformPen(pen, transform))
            yield pen
    for child in element:
        yield from geometry(child, transform)


def icon(key, data):
    root = ET.fromstring(data)
    if key == "aider":
        # The official pinned-tab asset is an inverse glyph in a square. Extract
        # the glyph, retaining all its interior contours and original transform.
        path = next(e for e in root.iter() if e.tag.endswith("}path"))
        path.attrib["d"] = path.attrib["d"].split("z", 1)[1].strip()
        assert path.attrib["d"].startswith("m2705")
        path.attrib["d"] = "M2705 3998" + path.attrib["d"][10:]
    if key in {"amp", "droid"}:
        # Favicon backgrounds are replaced by Harness's flat badge face.
        for parent in root.iter():
            for child in list(parent):
                if child.tag.endswith("}rect"):
                    parent.remove(child)
    paths = list(geometry(root))
    assert paths, key
    bounds = BoundsPen(None)
    for path in paths:
        path.replay(bounds)
    x0, y0, x1, y1 = bounds.bounds
    width, height = x1 - x0, y1 - y0
    scale = 24 / max(width, height)
    transform = Identity.translate((24 - width * scale) / 2, (24 - height * scale) / 2).scale(scale).translate(-x0, -y0)
    normalized = []
    for path in paths:
        pen = SVGPathPen(None, ntos=lambda n: format(n, ".6g"))
        path.replay(TransformPen(pen, transform))
        normalized.append(pen.getCommands())
    if key == "aider":
        normalized = [" ".join(normalized)]
    even_odd = key == "aider" or any(e.attrib.get("fill-rule") == "evenodd" for e in root.iter())
    return f'        "{key}": AgentVectorIcon(viewBox: CGSize(width: 24, height: 24), evenOdd: {str(even_odd).lower()}, subpaths: [\n' + "\n".join('            ' + json.dumps(p) + ',' for p in normalized) + '\n        ]),'


def main():
    catalog = json.loads((SOURCES / "sources.json").read_text())
    vectors, rasters = [], []
    for key, source in catalog.items():
        data = (SOURCES / source["file"]).read_bytes()
        assert hashlib.sha256(data).hexdigest() == source["sha256"], f"Source changed: {key}"
        if source["file"].endswith(".png"):
            rasters.append(f'        "{key}": "{base64.b64encode(data).decode()}",')
        else:
            vectors.append(icon(key, data))
    DESTINATION.write_text('''// Generated by Scripts/generate-agent-icons.py. Do not edit geometry by hand.
// Sources, pinned revisions, hashes and licenses: Resources/AgentLogos/sources.json.
// SVG paths are normalized to a 24-point square. Only the generic agent uses letters.
import CoreGraphics

struct AgentVectorIcon {
    let viewBox: CGSize
    let evenOdd: Bool
    let subpaths: [String]
}

enum AgentIconArt {
    static let icons: [String: AgentVectorIcon] = [
''' + '\n'.join(vectors) + '\n    ]\n\n    // Original upstream raster artwork, embedded so both build systems stay self-contained.\n    static let rasterImages: [String: String] = [\n' + '\n'.join(rasters) + '\n    ]\n}\n')
    notices = (SOURCES / "README.md").read_text() + "\n"
    for license_file in sorted((SOURCES / "licenses").glob("*.txt")):
        notices += "\n--- " + license_file.stem + " ---\n\n" + license_file.read_text()
    (ROOT / "Apps/Harness/Sources/HarnessApp/Resources/AgentLogoNotices.txt").write_text(notices)
    print(f"Generated {len(vectors)} vector marks and {len(rasters)} original raster mark")


if __name__ == "__main__":
    main()
