#!/usr/bin/env python3
"""Generate terminal width tables from pinned Unicode data, without host ICU dependencies.

python3 Scripts/generate-width-table.py [--ucd-dir /path/to/files] > \
  Packages/HarnessTerminalEngine/Sources/HarnessTerminalEngine/Width/CharacterWidthTable.swift

The optional directory contains the three pinned UCD files below.
Otherwise download those files from the versioned Unicode archive. Hash verification
makes both paths reproducible; update the version and hashes together for a UCD upgrade.
"""

import argparse
import hashlib
from pathlib import Path
from urllib.request import urlopen

VERSION = "18.0.0"
SOURCES = {
    "EastAsianWidth.txt": "a0cf29eacd00cfcaec4381c6b7c281685f18dbb4e7ff82b4076ccb342ca839aa",
    "extracted/DerivedGeneralCategory.txt": "d6b151d2d40ee9b1876d26f417980f45ffae47b6055ccf7203cb31f07a030f94",
    "DerivedCoreProperties.txt": "09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9",
}


def read_properties(name, directory):
    if directory:
        data = (directory / Path(name).name).read_bytes()
    else:
        with urlopen(f"https://www.unicode.org/Public/{VERSION}/ucd/{name}", timeout=30) as response:
            data = response.read()
    if hashlib.sha256(data).hexdigest() != SOURCES[name]:
        raise ValueError(f"{name}: checksum does not match Unicode {VERSION}")
    for line in data.decode("utf-8").splitlines():
        fields = line.split("#", 1)[0].strip()
        if not fields:
            continue
        interval, property_name = (field.strip() for field in fields.split(";")[:2])
        bounds = interval.split("..")
        yield int(bounds[0], 16), int(bounds[-1], 16), property_name


def runs(values, start=0):
    index = start
    while index < len(values):
        end = index + 1
        while end < len(values) and values[end] == values[index]:
            end += 1
        yield index, end - 1, values[index]
        index = end


def emit_array(name, swift_type, values, per_row=12):
    print(f"    static let {name}: [{swift_type}] = [")
    for index in range(0, len(values), per_row):
        print("        " + ", ".join(map(str, values[index:index + per_row])) + ",")
    print("    ]")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ucd-dir", type=Path)
    args = parser.parse_args()
    widths = bytearray([1]) * 0x110000
    # Preserve the UAX #11 default-wide unassigned CJK ranges, including future ideographs.
    for lower, upper in [(0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF),
                         (0x20000, 0x2FFFD), (0x30000, 0x3FFFD)]:
        widths[lower:upper + 1] = bytes([2]) * (upper - lower + 1)
    for lower, upper, category in read_properties("EastAsianWidth.txt", args.ucd_dir):
        if category in {"W", "F"}:
            widths[lower:upper + 1] = bytes([2]) * (upper - lower + 1)
    for lower, upper, category in read_properties("extracted/DerivedGeneralCategory.txt", args.ucd_dir):
        if category in {"Mn", "Me", "Cf", "Zl", "Zp"} and upper >= 0x300:
            lower = max(lower, 0x300)
            widths[lower:upper + 1] = bytes(upper - lower + 1)
    # Existing terminal policy: controls have no width; soft hyphen remains narrow.
    widths[:0x20] = bytes(0x20)
    widths[0x7F:0xA0] = bytes(0x21)
    extenders = bytearray(0x110000)
    for lower, upper, property_name in read_properties("DerivedCoreProperties.txt", args.ucd_dir):
        if property_name == "Grapheme_Extend":
            extenders[lower:upper + 1] = bytes([1]) * (upper - lower + 1)

    stage1, blocks, block_indices = [], [], {}
    for high in range(256):
        block = bytes(sum(widths[high * 256 + low + offset] << (offset * 2)
                          for offset in range(4)) for low in range(0, 256, 4))
        if block not in block_indices:
            block_indices[block] = len(blocks)
            blocks.append(block)
        stage1.append(block_indices[block])
    astral = [(lower, upper, width) for lower, upper, width in runs(widths, 0x10000) if width != 1]

    print("// GENERATED by Scripts/generate-width-table.py — DO NOT EDIT BY HAND.")
    print(f"// Unicode {VERSION}; source URLs and SHA-256 hashes are pinned in the generator.")
    print("// Data derived from the Unicode Character Database, © Unicode, Inc.")
    print("// License: https://www.unicode.org/license.txt\n")
    print("enum CharacterWidthTable {")
    print(f'    static let unicodeVersion = "{VERSION}"')
    print("    static let blockBytes = 64")
    emit_array("stage1", "UInt16", stage1, 16)
    emit_array("stage2", "UInt8", list(b"".join(blocks)), 32)
    emit_array("astralLo", "UInt32", [f"0x{lower:X}" for lower, _, _ in astral], 6)
    emit_array("astralHi", "UInt32", [f"0x{upper:X}" for _, upper, _ in astral], 6)
    emit_array("astralCode", "UInt8", [width for _, _, width in astral])
    for name, width in [("zeroWidthRanges", 0), ("wideRanges", 2)]:
        values = [f"0x{lower:04X} ... 0x{upper:04X}"
                  for lower, upper, value in runs(widths, 0x300) if value == width]
        emit_array(name, "ClosedRange<UInt32>", values, 4)
    emit_array("graphemeExtendRanges", "ClosedRange<UInt32>",
               [f"0x{lower:04X} ... 0x{upper:04X}" for lower, upper, value in runs(extenders) if value], 4)
    print("}")


if __name__ == "__main__":
    main()
